repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks: [{ id: check-yaml }, { id: check-json }, { id: end-of-file-fixer }, { id: trailing-whitespace }]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect=postgres"]
      - id: sqlfluff-fix
        args: ["--dialect=postgres"]
