repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect=postgres"]
      - id: sqlfluff-fix
        args: ["--dialect=postgres"]

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.83.10
    hooks:
      - id: trufflehog
        args: ["."]   # scans hele repo for secrets
