
name: "DB Change Request"
description: "Formell forespørsel om Supabase/Postgres-migrasjon"
title: "[DBCR] <kort tittel>"
labels: ["db-change","review-needed"]
body:
  - type: input
    id: env
    attributes: { label: Målmiljø, placeholder: "dev" }
    validations: { required: true }
  - type: input
    id: filename
    attributes: { label: Filnavn, placeholder: "YYYYMMDDHHMMSS_beskrivelse.sql" }
    validations: { required: true }
  - type: textarea
    id: sql
    attributes: { label: SQL-utkast, render: sql }
    validations: { required: true }
  - type: textarea
    id: rollout
    attributes:
      label: Zero-downtime plan
      value: "Expand:\nBackfill:\nSwitch:\nContract:"
