name: CI
on:
  pull_request:
    paths:
      - "supabase/migrations/*.sql"
      - "supabase/seeds/**"
jobs:
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install sqlfluff
      - run: sqlfluff lint --dialect postgres supabase
