name: Migrate DB
on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/*.sql"
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: auth via OIDC + hent SUPABASE_DB_URL_*
      - run: echo "supabase db push kommer her når secrets er på plass"
